name: nightly-build

on:
  push:
    branches: [ "main" ]
env:
  BUILD_CONFIGURATION: Release    # set this to the appropriate build configuration

jobs:
  build:
    name: nightly-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -p:VersionSuffix=$GITHUB_RUN_ID --configuration '${{ env.BUILD_CONFIGURATION }}'
    - name: Pack
      run: dotnet pack --no-restore -p:VersionSuffix=$GITHUB_RUN_ID --no-build --configuration '${{ env.BUILD_CONFIGURATION }}' --output ./artifacts
    - name: Publish to MyGet
      run: dotnet nuget push --source myget --api-key ${{ secrets.MYGET_API_KEY }} ./artifacts/*.nupkg --skip-duplicate
