name: nightly-build

on:
  push:
    branches: [ "main" ]
env:
  BUILD_CONFIGURATION: Release    # set this to the appropriate build configuration

jobs:
  build:
    name: nightly-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_PAT }}

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -p:VersionSuffix=ci-$GITHUB_RUN_ID --configuration '${{ env.BUILD_CONFIGURATION }}'
    - name: Pack
      run: dotnet pack --no-restore --no-build --configuration '${{ env.BUILD_CONFIGURATION }}' --output ./artifacts
    - name: Publish
      run: dotnet nuget push --source github --api-key ${{ secrets.GITHUB_PAT }} ./artifacts/*.nupkg --skip-duplicate
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_PAT }}